import { List, Settings } from 'lucide-react';

const AutoGeneration = ({ menuItems }) => {
  const handleGenerateList = (itemName) => {
    console.log(`Generating shopping list for ${itemName}`);
    // Implementation for generating shopping list
  };

  return (
    <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
      <h3 className="text-lg font-bold text-gray-800 mb-4 flex items-center gap-2">
        <List size={20} className="text-orange-500" />
        Auto-Generated Shopping Lists
      </h3>
      <div className="space-y-4">
        {menuItems.map((item, index) => (
          <div key={index} className="p-4 border border-gray-200 rounded-lg">
            <div className="flex justify-between items-start mb-3">
              <h4 className="font-medium text-gray-800">{item.name}</h4>
              <div className="flex items-center gap-2">
                {item.autoGenerated && (
                  <span className="bg-green-100 text-green-700 px-2 py-1 rounded-full text-xs">
                    Auto-generated
                  </span>
                )}
                <button className="text-orange-500 hover:text-orange-600">
                  <Settings size={16} />
                </button>
              </div>
            </div>
            <div className="flex flex-wrap gap-2 mb-3">
              {item.ingredients.map((ingredient, i) => (
                <span key={i} className="bg-gray-100 text-gray-700 px-2 py-1 rounded-full text-xs">
                  {ingredient}
                </span>
              ))}
            </div>
            <button 
              onClick={() => handleGenerateList(item.name)}
              className="bg-orange-500 text-white px-4 py-2 rounded-lg hover:bg-orange-600 transition-colors text-sm"
            >
              Generate Shopping List
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};

export default AutoGeneration;